In [7]:
import numpy as np
import time
import sys

# Array Declaration(dimension, shape, size, data type)


In [11]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [20]:
b = np.array([[5,6,7],[8,9,10]])
print(b)

[[ 5  6  7]
 [ 8  9 10]]


In [13]:
a*b

array([ 5, 12, 21])

In [21]:
#ndim: number of dimensions 
 
b.ndim

2

In [22]:
# get shape
a.shape

(3,)

In [24]:
#n*m n:columns and m: rows
b.shape

(2, 3)

In [26]:
#get type
a.dtype

dtype('int64')

In [27]:
#get total size
a.nbytes

24

# Accessing a value or array


In [34]:
#get a specific element [r,c] rows and column

b[0, 1]

6

In [39]:
#get a specific row
b[1,:]

array([ 8,  9, 10])

In [40]:
#get a specific column

b[:,1]

array([6, 9])

# Initializing all types of array

In [43]:
 #initializing different types of arrays
#All 0s matrix
 np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
#All 1s matrix

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
#Any other number
np.full((3,2), 7, dtype='int32')

array([[7, 7],
       [7, 7],
       [7, 7]], dtype=int32)

In [50]:
#full_like(reference from other matrix)

np.full_like(b,10)

array([[10, 10, 10],
       [10, 10, 10]])

In [54]:
#Random decimal numbers

np.random.rand(4,2)

array([[0.27388365, 0.23212963],
       [0.98040058, 0.97515469],
       [0.53788586, 0.46096784],
       [0.50363698, 0.66366934]])

In [58]:
#Random shape with random decimal numbers

np.random.random_sample(b.shape)

array([[0.97521413, 0.36610932, 0.42482902],
       [0.84781447, 0.1025441 , 0.52751929]])

In [64]:
#Random integer values (2 including ,8 exclusive)
np.random.randint(2,8, size=(3,2))

array([[5, 7],
       [7, 2],
       [6, 7]])

In [70]:
#The Identity Matrix (3 : 3 rows and 3 columns)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
#repeating an array

arr= np.array([[1,2,3], [4,5,6]])
r1 = np.repeat(arr,2, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


# Exercise - 1

In [89]:
query = np.ones((5,5), dtype = 'int')


z = np.zeros((3,3))
z[1,1] = 9


query[1:-1, 1:-1] = z
print(query)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Copying

In [94]:
#Copying one to another

a = np.array([1,2,3])
b=a
b[0] = 10

print(b)
print(a)

[10  2  3]
[10  2  3]


# Mathematics


In [95]:
#Mathematics

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [97]:
 a + 2

array([-1,  0,  1,  2])

In [99]:
a-2

array([-1,  0,  1,  2])

In [98]:
a * 2

array([2, 4, 6, 8])

In [100]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [101]:
a **2

array([ 1,  4,  9, 16])

In [107]:
#Linear Algebra

a = np.ones((2,3))
print(a)

b = np.full((3,2),  7)  #((rows, columns), value)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]
 [7 7]]


array([[21., 21.],
       [21., 21.]])

In [112]:
#Find the determinent of the matrix
#linalg.det(matrix name): linear algebra determinent(matrix name)

c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics


In [113]:
 stats = np.array([[1,2,3], [4,5,6]])
 stats

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
np.min(stats, axis=1)

array([1, 4])

In [117]:
np.max(stats)

6

In [118]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Re-Organizing Arrays


In [123]:
before = np.array([[2,3,4,5], [6,7,8,9]])
print(before)


after =  before.reshape((2,2,2))
print(after)

[[2 3 4 5]
 [6 7 8 9]]
[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]


# Vertically Stacking Vectors


In [125]:
#vstack: vertically stacks combines two array into one and returns the output
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [126]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

# Horizontal Stacking Vectors

In [132]:
#hstack: horizontal stack combines two array into one and returns the output
h1 = np.array([[1,2,3,4], [9,10,11,12]])
h2 = np.array([[5,6,7,8], [13,14,15,16]])

np.hstack([h1,h2])

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

# Miscellaneous (Loading data from file)


In [140]:
np.genfromtxt('data numpy.txt', delimiter= ',', dtype ='int')

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59, 60]])

In [150]:
data = np.genfromtxt('data numpy.txt', delimiter= ',')
data = data.astype('int32')
print(data)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]]


# Boolean Masking & Advanced Indexing

In [143]:
data[data > 50]

array([], dtype=int32)

In [145]:
#accessing values in an array with a list in numpy.
a =  np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [151]:
#values where the data value is greater then 50 and less then 100 will show us True.
((data > 50) & (data < 100) )

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True]])